### ISSUE TITLE
Fix java.lang.NullPointerException: Attempt to write to field 'java.util.ArrayList android.animation.AnimatorSet$Node.nodeDependents' on a null object reference in androidx.appcompat.widget.u.<init>

### ISSUE THREAD

**Issue by yassermzh** [alacolang/kolbeh#127]
### Stacktrace ###

androidx.appcompat.widget.u.<init>;

com.reactnativecommunity.slider.a.<init>;

com.reactnativecommunity.slider.ReactSliderManager$b.a;

com.facebook.yoga.YogaNodeJNIBase.measure;

com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayoutJNI;

com.facebook.yoga.YogaNodeJNIBase.a;

com.facebook.react.uimanager.b0.a;

com.facebook.react.uimanager.o0.a;

com.facebook.react.uimanager.o0.j;

com.facebook.react.uimanager.o0.a;

com.facebook.react.uimanager.UIManagerModule.onBatchComplete;

com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete;

com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete;

com.facebook.react.bridge.queue.NativeRunnable.run;

com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage;

com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run;

### Reason ###

java.lang.NullPointerException: Attempt to write to field 'java.util.ArrayList android.animation.AnimatorSet$Node.nodeDependents' on a null object reference

### Link to App Center ###

* [https://appcenter.ms/users/yassermzh/apps/kolbeh/crashes/errors/4055029151u](https://appcenter.ms/users/yassermzh/apps/kolbeh/crashes/errors/4055029151u)

**Comment by soroushmz** [comment]
@yassermzh  I searched online and looks like ReactSlider from [react-native-slider](https://github.com/callstack/react-native-slider) results in this error as you can find on [Issue](https://github.com/facebook/react-native/issues/9979) where people suggest using another slider [here](https://github.com/jeanregisser/react-native-slider) which has may more stars than the one above
