### ISSUE TITLE
Daily notification texts

### ISSUE THREAD

**Issue by parisapedraam** [alacolang/kolbeh#130]
Dear colleagues,
Please replace daily notification texts with these new ones:

۱- زیبای خفته
امروز در شکلات یک زیبای خفته پیدا می‌کنی

۲- نوای خوش
امروز در شکلات یک نوای خوش پیدا می‌کنی

۳- نوازشگر
امروز در شکلات یک نوازشگر پیدا می‌کنی

۴- خوشبو
امروز در شکلات یک خوشبو رو پیدا می‌کنی

۵- خوش طعم
امروز در شکلات یک خوش طعم رو پیدا می‌کنی

-------------------------------------------------
1- من مثبت
امروز در شکلات با من مثبت آشنا میشی

2- دیگران مثبت
امروز در شکلات از دیگران مثبت می‌نویسی

3- دنیای مثبت
امروز در شکلات به دنیای مثبت توجه می‌کنی

4- نشانه مثبت
امروز در شکلات یک نشانه مثبت انتخاب می‌کنی

5- شعار مثبت
امروز در شکلات شعار مثبت بینی رو انتخاب می‌کنی

------------------------------------------------------------------------------------------------------

1- بخشش من
امروز در شکلات یک بخشنده رو پیدا می‌کنی

2- بخشش دوستانم
امروز در شکلات یکی از دوستانت رو می‌بخشی

3- بخشش غیر دوستان
امروز در شکلات بخشنده‌تر میشی

4- شاه کلید بخشش
امروز در شکلات کلید بخششت رو انتخاب می‌کنی

5- صندوقچه بخشش
امروز به شکلات از صندوقچه بخششت بگو

--------------------------------------------------------------

1- دوست دلنشین
امروز به شکلات یک دوست دلنشین رو معرفی کن

2- ابراز احساس
امروز در شکلات به احساسات توجه می‌کنی

3- بیان فکر
امروز در شکلات به فکر توجه می‌کنی

4- پیام بدن
امروز در شکلات با پیام بدن آشنا میشی

5- لحن دلنشین
امروز در شکلات به لحن دلنشین توجه می‌کنی

-------------------------------------------------------------------

۱- گوش همدل
امروز در شکلات با گوش‌هات همدلی می‌کنی

۲-  شنیدن احساس
امروز در شکلات به احساسات گوش میدی

۳- آینه فکر
امروز در شکلات آینه میشی

۴- بدن همدل
امروز در شکلات بدنت همدلی می‌کنه

۵- نشانه همدلی
امروز به شکلات نشانه همدلی‌ت رو معرفی می‌کنی
------------------------------------------------------------------------------

۱- مهر با خود
امروز در شکلات به خودت مهربانی می‌کنی

۲- مهر در خانه
امروز در شکلات به خانواده‌ت مهربانی می‌کنی

۳- مهر با دوست
امروز در شکلات به دوستت مهربانی می‌کنی

۴- مهر با دنیا
امروز در شکلات به دنیا مهربانی می‌کنی

۵- نشانه مهر
امروز در شکلات نشانه مهربانیت رو انتخاب می‌کنی

------------------------------------------------------

۱- سپاس از خود
امروز در شکلات از خودت سپاسگزاری می‌کنی

۲- سپاس از خانواده
امروز در شکلات از خانواده ت سپاسگزاری می‌کنی

۳- سپاس از دوست
امروز در شکلات از دوستت سپاسگزاری می‌کنی

۴- سپاس از طبیعت
امروز در شکلات از طبیعت سپاسگزاری می‌کنی

۵- نشانه سپاس
امروز در شکلات نشانه سپاسگزاری رو انتخاب می‌کنی

--------------------------------------------------------

۱- من شگفت انگیز
امروز در شکلات به من شگفت انگیز توجه می‌کنی

۲- خانواده شگفت انگیز
امروز در شکلات به خانواده شگفت انگیزت توجه می‌کنی

۳- دوست شگفت انگیز
امروز در شکلات به دوست شگفت انگیزت توجه می‌کنی

۴- طبیعت شگفت انگیز
امروز در شکلات به طبیعت شگفت انگیز توجه می‌کنی

۵- نشانه شگفت انگیز
امروز در شکلات نشانه شگفت انگیز رو انتخاب می‌کنی

----------------------------------------------------

۱- موفقیت‌های من
امروز در شکلات به موفقیت‌هات افتخار می‌کنی

۲- یاران من
امروز در شکلات از یاران روزهای سخت می‌گی

۳- ذهن قوی
امروز در شکلات به ذهن قدرتمندت  توجه می‌کنی

۴- شعار روزهای سخت
امروز در شکلات شعار روزهای سخت رو انتخاب می‌کنی

۵- نشانه مقاومت
امروز در شکلات نشانه مقاومتت رو انتخاب می‌کنی

---------------------------------------------------

۱- من دوست داشتنی
امروز در شکلات به خودت می‌گی که چقدر دوست‌داشتنی هستی

۲- مهربانی‌های من
امروز در شکلات به خودت می‌گی که چقدر مهربان هستی

۳- هدف‌های من
امروز در شکلات به خودت اهدافت رو یادآوری می‌کنی

۴- مقاومت‌های من
امروز در شکلات به خودت مقاومت‌‌هات رو یادآوری می‌کنی

۵- من منحصر به فرد
از امروز تو سفیر شکلات می‌شی
 
Thanks

**Comment by soroushmz** [comment]
@parisapedraam I think this issue should have a "enhancement" tag not a "documentation" tag :)
