### ISSUE TITLE
Fix java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference in c.h.a.d.getCurrentPosition

### ISSUE THREAD

**Issue by yassermzh** [alacolang/kolbeh#132]
### Stacktrace ###

c.h.a.d.getCurrentPosition;

com.brentvatne.react.b$b.run;

### Reason ###

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference

### Link to App Center ###

* [https://appcenter.ms/users/yassermzh/apps/kolbeh/crashes/errors/473772311u](https://appcenter.ms/users/yassermzh/apps/kolbeh/crashes/errors/473772311u)

**Comment by soroushmz** [comment]
Maybe this issue [issue](https://github.com/react-native-video/react-native-video/issues/1989)?

**Comment by yassermzh** [comment]
@soroushmz do you want to fix this? otherwise, feel free to close this.
